from pathlib import Path

file_path = input("Enter the path of the .vm file: ").strip('"')

input_path = Path(file_path)
output_path = input_path.with_suffix(".asm")


def clean(line):
    line = line.split('//')[0]  # Remove comments
    line = line.strip() # Remove whitespace
    return line

def Parser(line):
    cleaned_line = clean(line)
    if not cleaned_line:
        return None
    parts = cleaned_line.split()
    command = parts[0]
    arg1 = parts[1] if len(parts) > 1 else None
    arg2 = parts[2] if len(parts) > 2 else None
    return command, arg1, arg2

def command_type(command):
    if command in ["push", "pop"]:
        return "C_PUSH" if command == "push" else "C_POP"
    # elif command in ["label", "goto", "if-goto"]:
        # return "C_LABEL" if command == "label" else ("C_GOTO" if command == "goto" else "C_IF")
    # elif command in ["function", "call"]:
        # return "C_FUNCTION" if command == "function" else "C_CALL"
    # elif command == "return":
        # return "C_RETURN"
    else:
        return "C_ARITHMETIC"


arithmetic_assembly = {

    "add": "@SP\nAM=M-1\nD=M\nA=A-1\nM=D+M\n",

    "sub": "@SP\nAM=M-1\nD=M\nA=A-1\nM=M-D\n",

    "neg": "@SP\nA=M-1\nM=-M\n",

    "eq": "@SP\nAM=M-1\nD=M\nA=A-1\nD=M-D\n@EQ_TRUE_{0}\nD;JEQ\n@SP\nA=M-1\nM=0\n@EQ_END_{0}\n0;JMP\n(EQ_TRUE_{0})\n@SP\nA=M-1\nM=-1\n(EQ_END_{0})\n",

    "gt": "@SP\nAM=M-1\nD=M\nA=A-1\nD=M-D\n@GT_TRUE_{0}\nD;JGT\n@SP\nA=M-1\nM=0\n@GT_END_{0}\n0;JMP\n(GT_TRUE_{0})\n@SP\nA=M-1\nM=-1\n(GT_END_{0})\n",

    "lt": "@SP\nAM=M-1\nD=M\nA=A-1\nD=M-D\n@LT_TRUE_{0}\nD;JLT\n@SP\nA=M-1\nM=0\n@LT_END_{0}\n0;JMP\n(LT_TRUE_{0})\n@SP\nA=M-1\nM=-1\n(LT_END_{0})\n",
    
    "and": "@SP\nAM=M-1\nD=M\nA=A-1\nM=D&M\n",

    "or": "@SP\nAM=M-1\nD=M\nA=A-1\nM=D|M\n",

    "not": "@SP\nA=M-1\nM=!M\n"
}
 

def translate_arithmetic(command):
        translate_arithmetic.counter += 1
        return arithmetic_assembly[command].format(translate_arithmetic.counter)

translate_arithmetic.counter = 0

ASS = {
    "constant": "@{0}\nD=A\n",
    "part2": "@{0}\nD=M\n@{1}\nA=D+A\nD=M\n",
    "temp": "@{0}\nD=A\n@{1}\nA=D+A\nD=M\n",
    "static": "@{0}.{1}\nD=M\n",
    "push": "@SP\nA=M\nM=D\n@SP\nM=M+1\n\n"
}

LOCATION_BASES = {
    "local": "LCL",
    "argument": "ARG",
    "this": "THIS",
    "that": "THAT",
    "temp": "5",
}


def translate_push(segment, index, input_path):
    if segment == "constant":
        return ASS[segment].format(index)  + ASS["push"]
    elif segment in ["local", "argument", "this", "that"]:
        base = LOCATION_BASES[segment]
        # return f"@{base}\nD=M\n@{index}\nA=D+A\nD=M\n" + ASS["push"]
        return ASS["part2"].format(base,index) + ASS["push"]
    elif segment == "temp":
        base = LOCATION_BASES[segment]
        # return f"@{base}\nD=A\n@{index}\nA=D+A\nD=M\n" + ASS["push"]
        return ASS["temp"].format(base,index) + ASS["push"]
    elif segment == "pointer":
        if index == "0":
            return "@THIS\nD=M\n" + ASS["push"]
        elif index == "1":
            return "@THAT\nD=M\n" + ASS["push"]
    elif segment == "static":
        return ASS["static"].format(input_path.stem, index) + ASS["push"]

def translate_pop(segment, index, input_path):
    if segment in ["local", "argument", "this", "that"]:
        base = LOCATION_BASES[segment]
        return f"@{base}\nD=M\n@{index}\nD=D+A\n@R13\nM=D\n@SP\nAM=M-1\nD=M\n@R13\nA=M\nM=D\n"
    elif segment == "temp":
        base = LOCATION_BASES[segment]
        return f"@{base}\nD=A\n@{index}\nD=D+A\n@R13\nM=D\n@SP\nAM=M-1\nD=M\n@R13\nA=M\nM=D\n"
    elif segment == "pointer":
        if index == "0":
            return "@SP\nAM=M-1\nD=M\n@THIS\nM=D\n"
        elif index == "1":
            return "@SP\nAM=M-1\nD=M\n@THAT\nM=D\n"
    elif segment == "static":
        return f"@SP\nAM=M-1\nD=M\n@{input_path.stem}.{index}\nM=D\n"


with open(input_path, "r") as vm_file, open(output_path, "w") as asm_file:
    asm_file.write("// This file is generated by VM-Translator.py Abo Bakr edition\n")
    asm_file.write("// written by Abo Bakr\n")
    asm_file.write("// spoof0x0 was here\n")
    asm_file.write("\n")

    for line in vm_file:
        parsed = Parser(line)

        if parsed:
            command, arg1, arg2 = parsed
            cmd_type = command_type(command)
            if cmd_type == "C_ARITHMETIC":
                assembly_code = translate_arithmetic(command)
                asm_file.write(assembly_code)
            elif cmd_type == "C_PUSH":
                assembly_code = translate_push(arg1, arg2, input_path)
                asm_file.write(assembly_code)
            elif cmd_type == "C_POP":
                assembly_code = translate_pop(arg1, arg2, input_path)
                asm_file.write(assembly_code)

    