// This file is generated by VM-Translator.py Abo Bakr edition
// written by Abo Bakr
// spoof0x0 was here

@7
D=A
@SP
A=M
M=D
@SP
M=M+1

@8
D=A
@SP
A=M
M=D
@SP
M=M+1

@SP
AM=M-1
D=M
A=A-1
M=D+M
